version: '3.8'

services:

  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: securevoting
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d securevoting"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - securevoting_net

  backend:
    build:
      context: ../backend/SecureVotingSystem
      dockerfile: ../Dockerfile
    depends_on:
      - postgres
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=securevoting;Username=postgres;Password=postgres
      - MailSettings__Host=smtp.gmail.com
      - MailSettings__Port=587
      - MailSettings__EnableSsl=true
      - MailSettings__SenderEmail=warblank21@gmail.com
      - MailSettings__SenderName=Secure Voting System
      - MailSettings__Username=warblank21@gmail.com
      - MailSettings__Password=ukvdhnwzpersorna
    ports:
      - "5000:5000"
    networks:
      - securevoting_net

  frontend:
    build:
      context: ../frontend
      args:
        VITE_API_BASE: "http://localhost:5000/api"
    depends_on:
      - backend
    ports:
      - "5173:80"
    networks:
      - securevoting_net

  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    restart: unless-stopped
    user: root
    privileged: true
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - securevoting_net

  prometheus:
    image: prom/prometheus
    restart: unless-stopped
    volumes:
      - ../prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - securevoting_net

  grafana:
    image: grafana/grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ../grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
      - ../grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ../grafana/dashboards:/var/lib/grafana/dashboards:ro
    networks:
      - securevoting_net

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - securevoting_net

volumes:
  postgres-data:
  jenkins-data:
  prometheus-data:
  grafana-data:
  pgadmin-data:

networks:
  securevoting_net:
    driver: bridge