pipeline {
  agent any

  stages {

    stage('Checkout') {
      steps {
        git url: 'https://your-repo-url.git'
      }
    }

    stage('Build Backend') {
      steps {
        sh '''
          cd backend/SecureVotingSystem
          dotnet restore
          dotnet build -c Release
        '''
      }
    }

    stage('Build Frontend') {
      steps {
        sh '''
          cd frontend
          npm ci
          npm run build
        '''
      }
    }

    stage('Docker Build') {
      steps {
        sh 'docker compose build'
      }
    }

    stage('Deploy') {
      steps {
        sh 'docker compose up -d --build'
      }
    }

    stage('Health Check') {
      steps {
        sh 'curl -f http://localhost:5000/metrics'
      }
    }
  }
}